const originalBookList = [
  {
    title: "Aprendendo JavaScript Básico",
    author: "John Doe",
    pages: 200,
    condition: "novo",
  },
  {
    title: "HTML e CSS Desvendados",
    author: "Jane Smith",
    pages: 150,
    condition: "desgastado",
  },
  {
    title: "Node.js para Iniciantes",
    author: "Bob Johnson",
    pages: 250,
    condition: "conservado",
  },
  {
    title: "React.js na Prática",
    author: "Alice Green",
    pages: 180,
    condition: "novo",
  },
  {
    title: "PHP e MySQL para Web",
    author: "Charles Brown",
    pages: 220,
    condition: "desgastado",
  },
  {
    title: "Python para Data Science",
    author: "David Lee",
    pages: 300,
    condition: "novo",
  },
  {
    title: "Ruby on Rails em 24 Horas",
    author: "Emma White",
    pages: 240,
    condition: "conservado",
  },
  {
    title: "Java para Desenvolvedores Android",
    author: "Frank Black",
    pages: 280,
    condition: "novo",
  },
  {
    title: "C# e .NET para Jogos",
    author: "Grace Kim",
    pages: 260,
    condition: "desgastado",
  },
  {
    title: "Laravel: O Framework PHP Moderno",
    author: "Henry Jones",
    pages: 210,
    condition: "novo",
  },
  {
    title: "Django: O Framework Python Completo",
    author: "Iris Wang",
    pages: 270,
    condition: "conservado",
  },
  {
    title: "Angular: O Framework JavaScript Poderoso",
    author: "James Smith",
    pages: 230,
    condition: "novo",
  },
  {
    title: "Swift: A Linguagem da Apple",
    author: "Kelly Clark",
    pages: 190,
    condition: "desgastado",
  },
  {
    title: "WordPress: O CMS Mais Popular do Mundo",
    author: "Laura Miller",
    pages: 160,
    condition: "novo",
  },
  {
    title: "MongoDB: O Banco de Dados NoSQL",
    author: "Mark Wilson",
    pages: 200,
    condition: "conservado",
  },
  {
    title: "Bootstrap: O Framework CSS Responsivo",
    author: "Nancy Davis",
    pages: 140,
    condition: "novo",
  },
  {
    title: "Vue.js: O Framework JavaScript Simples",
    author: "Oscar Lopez",
    pages: 170,
    condition: "desgastado",
  },
  {
    title: "Flask: O Microframework Python",
    author: "Rachel Adams",
    pages: 150,
    condition: "novo",
  },
  {
    title: "Sass: O Pré-processador CSS",
    author: "Scott Baker",
    pages: 130,
    condition: "conservado",
  },
  {
    title: "TypeScript: O JavaScript Tipado",
    author: "Zoe Taylor",
    pages: 190,
    condition: "novo",
  },
];
